#!/usr/bin/env bash

####################################################################
# bl - BLACKLIST CHECK UNIX/LINUX UTILITY                          #
# copyright: (c) 2014 Anders Aarvik                                #
# author: Anders Aarvik (aarvik92@gmail.com) and contributors      #
# license: MIT licensed. See LICENSE                               #
# description: I was just a bit tired of web interfaces            #
####################################################################

which ggrep 2> /dev/null > /dev/null && GREP_CMD="ggrep" || GREP_CMD="grep"

#### main ####
main() {

  [ $# -ne 1 ] && error "Please specify a FQDN or IP as a parameter."

  fqdn=$(echo $1 | $GREP_CMD -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")

  if [[ $fqdn ]] ; then

    echo "You entered a domain: $1"

    domain=$(host $1 | head -n1 | awk '{print $4}')

    reverseit $domain "IP not valid or domain could not be resolved."
  else

    echo "You entered an IP: $1"
    reverseit $1 "IP not valid."
  fi

  loopthroughblacklists $1
}

#### reverseit ####
reverseit() {

  reverse=$(echo $1 |
  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")

  if [ "x${reverse}" = "x" ] ; then

    error $2 
    exit 1
  fi
}

echo " "
#### loopthroughblacklists ####
loopthroughblacklists() {

  reverse_dns=$(dig +short -x $1)

  echo $1 name ${reverse_dns:----}

  for bl in ${blacklists} ; do
      #printf $(env tz=utc date "+%y-%m-%d_%h:%m:%s_%z")
      #printf "%-40s" " ${reverse}.${bl}."

      listed="$(dig +short -t a ${reverse}.${bl}.)"

      if [[ $listed ]]; then

        if [[ $listed == *"timed out"* ]]; then

          echo "$bl [timed out]" | cecho YELLOW 
        else
        
          echo "$bl [blacklisted] (${listed})" | cecho LRED
        fi
      else

          echo "$bl [not listed]" | cecho LGREEN
      fi
  done
}

#### error ####
error() {

  echo $0 error: $1 >&2
  exit 2
}

#### cecho ####
cecho(){

  LGREEN="\033[1;32m"
  LRED="\033[1;31m"
  YELLOW="\033[1;33m"
  NORMAL="\033[m"
 
  color=\$${1:-NORMAL}
 
  echo -ne "$(eval echo ${color})"
  cat
 
  echo -ne "${NORMAL}"
}

#### Updated at 2021-04-28 from: ####
#### blacklists - grabbed from https://hetrixtools.com/blacklist-check ####
#### blacklists - grabbed from https://glockapps.com/blacklist/dnsrbl-org/ ####
#### Blacklists - Source TavoWEB ####
blacklists="
0spam.fusionzero.com
0spam-n.fusionzero.com
0spamtrust.fusionzero.com
0spamurl.fusionzero.com
access.redhawk.org
all.s5h.net
all.spamrats.com
aspews.ext.sorbs.net
babl.rbl.webiron.net
backscatter.spameatingmonkey.net
badconf.rhsbl.sorbs.net
b.barracudacentral.org
bb.barracudacentral.org
bl.0spam.org
black.junkemailfilter.com
blacklist.netcore.co.in
bl.blocklist.de
bl.drmx.org
bl.fmb.la
bl.konstant.no
bl.mailspike.net
bl.nosolicitado.org
block.dnsbl.sorbs.net
bl.rbl.scrolloutf1.com
bl.scientificspam.net
bl.score.senderscore.com
bl.spamcop.net
bl.spameatingmonkey.net
bl.suomispam.net
bsb.empty.us
bsb.spamlookup.net
cart00ney.surriel.com
cbl.abuseat.org
cbl.anti-spam.org.cn
cblless.anti-spam.org.cn
cblplus.anti-spam.org.cn
cdl.anti-spam.org.cn
combined.rbl.msrbl.net
dblack.mail.abusix.zone
dbl.spamhaus.org
dbl.tiopan.com
db.wpbl.info
dnsbl-1.uceprotect.net
dnsbl-2.uceprotect.net
dnsbl-3.uceprotect.net
dnsbl.cobion.com
dnsbl.dronebl.org
dnsbl.justspam.org
dnsbl.kempt.net
dnsbl.net.ua
dnsbl.rv-soft.info
dnsbl.rymsho.ru
dnsbl.sorbs.net
dnsbl.spfbl.net
dnsbl.tornevall.org
dnsbl.zapbl.net
dnsrbl.swinog.ch
dul.dnsbl.sorbs.net
dyna.spamrats.com
escalations.dnsbl.sorbs.net
fnrbl.fast.net
hostkarma.junkemailfilter.com
http.dnsbl.sorbs.net
images.rbl.msrbl.net
invaluement
ips.backscatterer.org
ix.dnsbl.manitu.net
l1.bbfh.ext.sorbs.net
l2.bbfh.ext.sorbs.net
l4.bbfh.ext.sorbs.net
list.bbfh.org
mail-abuse.blacklist.jippg.org
misc.dnsbl.sorbs.net
multi.surbl.org
nbl.0spam.org
netscan.rbl.blockedservers.com
new.spam.dnsbl.sorbs.net
nomail.rhsbl.sorbs.net
noptr.spamrats.com
nordSpam.com
nsbl.fmb.la
old.spam.dnsbl.sorbs.net
pbl.spamhaus.org
phishing.rbl.msrbl.net
pofon.foobar.hu
problems.dnsbl.sorbs.net
proxies.dnsbl.sorbs.net
psbl.surriel.com
rbl2.triumf.ca
rbl.abuse.ro
rbl.blockedservers.com
rbl.dns-servicios.com
rbl.efnet.org
rbl.efnetrbl.org
rbl.interserver.net
rbl.realtimeblacklist.com
rbl.schulte.org
recent.spam.dnsbl.sorbs.net
relays.dnsbl.sorbs.net
rep.mailspike.net
rhsbl.scientificspam.net
rhsbl.sorbs.net
rhsbl.zapbl.net
safe.dnsbl.sorbs.net
sbl.spamhaus.org
short.fmb.la
smtp.dnsbl.sorbs.net
socks.dnsbl.sorbs.net
spam.dnsbl.anonmails.de
spam.dnsbl.sorbs.net
spamlist.or.kr
spam.pedantic.org
spam.rbl.blockedservers.com
spamrbl.imp.ch
spam.rbl.msrbl.net
spamsources.fabel.dk
spam.spamrats.com
srn.surgate.net
stabl.rbl.webiron.net
st.technovision.dk
talosintelligence.com
torexit.dan.me.uk
truncate.gbudb.net
ubl.unsubscore.com
uribl.abuse.ro
uribl.com
uribl.pofon.foobar.hu
uribl.spameatingmonkey.net
uribl.swinog.ch
url.0spam.org
virus.rbl.msrbl.net
web.dnsbl.sorbs.net
web.rbl.msrbl.net
wl.0spam.org
xbl.spamhaus.org
zen.spamhaus.org
z.mailspike.net
zombie.dnsbl.sorbs.net
bl.0spam.org
0spam.fusionzero.com
nbl.0spam.org
0spam-n.fusionzero.com
url.0spam.org
0spamurl.fusionzero.com
uribl.zeustracker.abuse.ch
ipbl.zeustracker.abuse.ch
rbl.abuse.ro
uribl.abuse.ro
spam.dnsbl.anonmails.de
dnsbl.anticaptcha.net
orvedb.aupads.org
rsbl.aupads.org
block.ascams.com
dnsbl.ascams.com
superblock.ascams.com
aspews.ext.sorbs.net
ips.backscatterer.org
b.barracudacentral.org
bb.barracudacentral.org
list.bbfh.org
l1.bbfh.ext.sorbs.net
l2.bbfh.ext.sorbs.net
l3.bbfh.ext.sorbs.net
l4.bbfh.ext.sorbs.net
netscan.rbl.blockedservers.com
rbl.blockedservers.com
spam.rbl.blockedservers.com
list.blogspambl.com
bsb.empty.us
bsb.empty.us
bsb.spamlookup.net
bsb.spamlookup.net
black.dnsbl.brukalai.lt
black.dnsbl.brukalai.lt
light.dnsbl.brukalai.lt
light.dnsbl.brukalai.lt
blacklist.sci.kun.nl
cbl.abuseat.org
bogons.cymru.com
v4.fullbogons.cymru.com
torexit.dan.me.uk
dnsbl.darklist.de
openproxy.bls.digibase.ca
proxyabuse.bls.digibase.ca
spambot.bls.digibase.ca
rbl.dns-servicios.com
dnsbl.beetjevreemd.nl
dnsbl.calivent.com.pe
dnsbl.isx.fr
dnsbl.net.ua
dnsbl.rv-soft.info
dnsblchile.org
vote.drbl.caravan.ru
work.drbl.caravan.ru
vote.drbl.gremlin.ru
work.drbl.gremlin.ru
bl.drmx.org
dnsbl.dronebl.org
dul.pacifier.net
rbl.efnet.org
rbl.efnetrbl.org
tor.efnet.org
rbl.fasthosts.co.uk
bl.fmb.la
bl.fmb.la
communicado.fmb.la
nsbl.fmb.la
short.fmb.la
fnrbl.fast.net
forbidden.icm.edu.pl
hil.habeas.com
black.junkemailfilter.com
black.junkemailfilter.com
dnsbl.cobion.com
spamrbl.imp.ch
wormrbl.imp.ch
rbl.interserver.net
rbl.iprange.net
rbl.ircbl.org
mail-abuse.blacklist.jippg.org
dnsbl.justspam.org
dnsbl.kempt.net
spamlist.or.kr
bl.konstant.no
relays.bl.kundenserver.de
spamguard.leadmon.net
rbl.lugh.ch
dnsbl.madavi.de
iprbl.mailcleaner.net
niprbl.mailcleaner.net
nuribl.mailcleaner.net
uribl.mailcleaner.net
bl.mailspike.net
z.mailspike.net
bl.mav.com.br
cidr.bl.mcafee.com
rbl.metunet.com
combined.rbl.msrbl.net
images.rbl.msrbl.net
phishing.rbl.msrbl.net
spam.rbl.msrbl.net
virus.rbl.msrbl.net
web.rbl.msrbl.net
relays.nether.net
unsure.nether.net
ix.dnsbl.manitu.net
dbl.nordspam.com
bl.nordspam.com
bl.nosolicitado.org
bl.worst.nosolicitado.org
sbl.nszones.com
ubl.nszones.com
bl.octopusdns.com
spam.pedantic.org
pofon.foobar.hu
uribl.pofon.foobar.hu
bl.rbl.polspam.pl
bl-h1.rbl.polspam.pl
bl-h2.rbl.polspam.pl
bl-h3.rbl.polspam.pl
bl-h4.rbl.polspam.pl
cnkr.rbl.polspam.pl
dyn.rbl.polspam.pl
lblip4.rbl.polspam.pl
rblip4.rbl.polspam.pl
rhsbl.rbl.polspam.pl
rhsbl-h.rbl.polspam.pl
psbl.surriel.com
rbl.rbldns.ru
rbl.schulte.org
rbl.realtimeblacklist.com
access.redhawk.org
abuse.rfc-clueless.org
bogusmx.rfc-clueless.org
dsn.rfc-clueless.org
elitist.rfc-clueless.org
fulldom.rfc-clueless.org
postmaster.rfc-clueless.org
mailsl.dnsbl.rjek.com
urlsl.dnsbl.rjek.com
uribl.rspamd.com
dnsbl.rymsho.ru
rhsbl.rymsho.ru
all.s5h.net
public.sarbl.org
rhsbl.scientificspam.net
bl.scientificspam.net
bl.score.senderscore.com
singular.ttk.pte.hu
dnsbl.sorbs.net
problems.dnsbl.sorbs.net
proxies.dnsbl.sorbs.net
relays.dnsbl.sorbs.net
safe.dnsbl.sorbs.net
nomail.rhsbl.sorbs.net
badconf.rhsbl.sorbs.net
dul.dnsbl.sorbs.net
zombie.dnsbl.sorbs.net
block.dnsbl.sorbs.net
escalations.dnsbl.sorbs.net
http.dnsbl.sorbs.net
misc.dnsbl.sorbs.net
smtp.dnsbl.sorbs.net
socks.dnsbl.sorbs.net
rhsbl.sorbs.net
spam.dnsbl.sorbs.net
recent.spam.dnsbl.sorbs.net
new.spam.dnsbl.sorbs.net
old.spam.dnsbl.sorbs.net
web.dnsbl.sorbs.net
korea.services.net
backscatter.spameatingmonkey.net
bl.spameatingmonkey.net
fresh.spameatingmonkey.net
fresh10.spameatingmonkey.net
fresh15.spameatingmonkey.net
fresh30.spameatingmonkey.net
freshzero.spameatingmonkey.net
netbl.spameatingmonkey.net
uribl.spameatingmonkey.net
urired.spameatingmonkey.net
netblockbl.spamgrouper.to
bl.spamcop.net
sbl.spamdown.org
dbl.spamhaus.org
pbl.spamhaus.org
sbl.spamhaus.org
sbl-xbl.spamhaus.org
xbl.spamhaus.org
zen.spamhaus.org
feb.spamlab.com
rbl.spamlab.com
all.spamrats.com
auth.spamrats.com
dyna.spamrats.com
noptr.spamrats.com
spam.spamrats.com
spamsources.fabel.dk
dnsbl.spfbl.net
dnsbl.spfbl.net
bl.suomispam.net
dbl.suomispam.net
gl.suomispam.net
multi.surbl.org
multi.surbl.org
dnsrbl.swinog.ch
uribl.swinog.ch
st.technovision.dk
dob.sibl.support-intelligence.net
dnsbl.tornevall.org
rbl2.triumf.ca
truncate.gbudb.net
dnsbl-0.uceprotect.net
dnsbl-1.uceprotect.net
dnsbl-2.uceprotect.net
dnsbl-3.uceprotect.net
ubl.unsubscore.com
black.uribl.com
grey.uribl.com
multi.uribl.com
red.uribl.com
free.v4bl.org
ip.v4bl.org
blacklist.woody.ch
uri.blacklist.woody.ch
db.wpbl.info
bl.blocklist.de
dnsbl.zapbl.net
rhsbl.zapbl.net
d.bl.zenrbl.pl
ip4.bl.zenrbl.pl
sa.fmb.la
hostkarma.junkemailfilter.com
hostkarma.junkemailfilter.com
nobl.junkemailfilter.com
nobl.junkemailfilter.com
krn.korumail.com
rep.mailspike.net
reputation-domain.rbl.scrolloutf1.com
reputation-ip.rbl.scrolloutf1.com
reputation-ns.rbl.scrolloutf1.com
score.senderscore.com
score.spfbl.net
score.spfbl.net
srn.surgate.net
0spamtrust.fusionzero.com
query.bondedsender.org
plus.bondedsender.org
white.dnsbl.brukalai.lt
white.dnsbl.brukalai.lt
whitelist.sci.kun.nl
dwl.dnswl.org
list.dnswl.org
accredit.habeas.com
sa-accredit.habeas.com
hul.habeas.com
sohul.habeas.com
iadb.isipp.com
iadb2.isipp.com
iddb.isipp.com
wadb.isipp.com
wl.mailspike.net
trusted.nether.net
wl.nszones.com
ispmx.pofon.foobar.hu
ip4.white.polspam.pl
whitelist.surriel.com
eswlrev.dnsbl.rediris.es
mtawlrev.dnsbl.rediris.es
_vouch.dwl.spamhaus.org
swl.spamhaus.org
dnswl.spfbl.net
dnswl.spfbl.net
wbl.triumf.ca
white.uribl.com
ips.whitelisted.org
abuse-contacts.abusix.org
all.ascc.dnsbl.bit.nl
all.dnsbl.bit.nl
bitonly.dnsbl.bit.nl
zz.countries.nerd.dk
origin.asn.cymru.com
peer.asn.cymru.com
tor.dan.me.uk
asn.routeviews.org
aspath.routeviews.org
query.senderbase.org
sa.senderbase.org
rf.senderbase.org
geobl.spameatingmonkey.net
origin.asn.spameatingmonkey.net
abuse.spfbl.net
abuse.spfbl.net
"

### initiate script ###
main $1
