#!/usr/bin/env bash

####################################################################
# bl - BLACKLIST CHECK UNIX/LINUX UTILITY                          #
# copyright: (c) 2014 Anders Aarvik                                #
# author: Anders Aarvik (aarvik92@gmail.com) and contributors      #
# license: MIT licensed. See LICENSE                               #
# description: I was just a bit tired of web interfaces            #
####################################################################

which ggrep 2> /dev/null > /dev/null && GREP_CMD="ggrep" || GREP_CMD="grep"

#### main ####
main() {

  [ $# -ne 1 ] && error "Please specify a FQDN or IP as a parameter."

  fqdn=$(echo $1 | $GREP_CMD -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")

  if [[ $fqdn ]] ; then

    echo "You entered a domain: $1"

    domain=$(host $1 | head -n1 | awk '{print $4}')

    reverseit $domain "IP not valid or domain could not be resolved."
  else

    echo "You entered an IP :) : $1"
    reverseit $1 "IP not valid."
  fi

  loopthroughblacklists $1
}

#### reverseit ####
reverseit() {

  reverse=$(echo $1 |
  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")

  if [ "x${reverse}" = "x" ] ; then

    error $2 
    exit 1
  fi
}

echo " "
#### loopthroughblacklists ####
loopthroughblacklists() {

  reverse_dns=$(dig +short -x $1)

  echo $1 name ${reverse_dns:----}

  for bl in ${blacklists} ; do
      #printf $(env tz=utc date "+%y-%m-%d_%h:%m:%s_%z")
      #printf "%-40s" " ${reverse}.${bl}."

      listed="$(dig +short -t a ${reverse}.${bl}.)"

      if [[ $listed ]]; then

        if [[ $listed == *"timed out"* ]]; then

          echo "$bl [timed out]" | cecho YELLOW 
        else
        
          echo "$bl [blacklisted] (${listed})" | cecho LRED
        fi
      else

          echo "$bl [not listed]" | cecho LGREEN
      fi
  done
}

#### error ####
error() {

  echo $0 error: $1 >&2
  exit 2
}

#### cecho ####
cecho(){

  LGREEN="\033[1;32m"
  LRED="\033[1;31m"
  YELLOW="\033[1;33m"
  NORMAL="\033[m"
 
  color=\$${1:-NORMAL}
 
  echo -ne "$(eval echo ${color})"
  cat
 
  echo -ne "${NORMAL}"
}



#### Updated at 2023-12-12 from: ####
#### blacklists - grabbed from https://hetrixtools.com/blacklist-check ####
#### blacklists - grabbed from https://glockapps.com/blacklist/dnsrbl-org/ ####
#### blacklists - grabbed from updated list at slurp-ramen.com ####
#### Blacklists - Source TavoWEB ####
blacklists="
0spam-killlist.fusionzero.com
ipbl.zeustracker.abuse.ch
rbl.abuse.ro
spam.dnsbl.anonmails.de
dnsbl.anticaptcha.net
orvedb.aupads.org
rsbl.aupads.org
block.ascams.com
superblock.ascams.com
aspews.ext.sorbs.net
ips.backscatterer.org
b.barracudacentral.org
list.bbfh.org
blackholes.tepucom.nl
netscan.rbl.blockedservers.com
rbl.blockedservers.com
spam.rbl.blockedservers.com
list.blogspambl.com
blacklist.sci.kun.nl
cbl.anti-spam.org.cn
cblplus.anti-spam.org.cn
cblless.anti-spam.org.cn
cdl.anti-spam.org.cn
bogons.cymru.com
v4.fullbogons.cymru.com
rbl.dns-servicios.com
dnsblchile.org
bl.drmx.org
dnsbl.dronebl.org
rbl.fasthosts.co.uk
fnrbl.fast.net
forbidden.icm.edu.pl
black.junkemailfilter.com
dnsbl.cobion.com
spamrbl.imp.ch
wormrbl.imp.ch
rbl.interserver.net
mail-abuse.blacklist.jippg.org
dnsbl.justspam.org
dnsbl.kempt.net
spamlist.or.kr
bl.mailspike.net
z.mailspike.net
bl.mav.com.br
cidr.bl.mcafee.com
images.rbl.msrbl.net
phishing.rbl.msrbl.net
spam.rbl.msrbl.net
relays.nether.net
unsure.nether.net
spam.pedantic.org
psbl.surriel.com
rbl.schulte.org
bl.scientificspam.net
dnsbl.sorbs.net
proxies.dnsbl.sorbs.net
relays.dnsbl.sorbs.net
dul.dnsbl.sorbs.net
zombie.dnsbl.sorbs.net
block.dnsbl.sorbs.net
escalations.dnsbl.sorbs.net
smtp.dnsbl.sorbs.net
socks.dnsbl.sorbs.net
spam.dnsbl.sorbs.net
recent.spam.dnsbl.sorbs.net
new.spam.dnsbl.sorbs.net
backscatter.spameatingmonkey.net
badnets.spameatingmonkey.net
bl.spameatingmonkey.net
netbl.spameatingmonkey.net
bl.spamcop.net
sbl.spamdown.org
spamsources.fabel.dk
bl.suomispam.net
gl.suomispam.net
multi.surbl.org
dnsrbl.swinog.ch
rbl2.triumf.ca
truncate.gbudb.net
dnsbl-0.uceprotect.net
dnsbl-1.uceprotect.net
dnsbl-2.uceprotect.net
dnsbl-3.uceprotect.net
blacklist.woody.ch
db.wpbl.info
bl.blocklist.de
"

### initiate script ###
main $1
